-- [Ⅷ] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PRIMARY KEY 용도로 사용
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 100
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 100
    NOCACHE    --컴퓨터 껏다가 켜도 순차적으로 이어짐. 입력할 것을 추천!
    NOCYCLE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4),  -- 시퀀스 이용
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDRESS VARCHAR2(100),
    LAST_MODIFIED DATE DEFAULT SYSDATE,
    PRIMARY KEY(NUM) );
    
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, 'KEYNES', NULL, '서울시 마포구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES(FRIEND_SEQ.NEXTVAL, 'EINSTEIN', '010-1234-5678', '서울시 양천구');
SELECT * FROM FRIEND;
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, 'MARX', '010-1234-5678', '서울시 종로구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS)
    VALUES (FRIEND_SEQ.NEXTVAL, 'ALI', '010-4321-9876', '서울시 강서구');
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;    -- 현재 시퀀스 값.
COMMIT;

CREATE SEQUENCE TEST_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_SEQ.CURRVAL FROM DUAL;