CREATE SEQUENCE ORDER_SEQ
    START WITH 1
    NOCYCLE;

CREATE TABLE MEMBER(
    mID VARCHAR2(20) PRIMARY KEY,
    mNAME VARCHAR2(50),
    mPHONE VARCHAR2(20) );
    
CREATE TABLE PRODUCT(
    pCODE VARCHAR2(20) PRIMARY KEY,
    pNAME VARCHAR2(100) NOT NULL,
    pPRICE NUMBER(20) );
    
CREATE TABLE ORDERS(
    oNum NUMBER(20) PRIMARY KEY,
    oDATE DATE DEFAULT SYSDATE,
    rADDRESS VARCHAR2(100) NOT NULL,
    RECIPIENT VARCHAR2(20) NOT NULL,
    oQTY NUMBER(4),
    mID VARCHAR2(20) REFERENCES MEMBER(mID),
    pCODE VARCHAR2(20) REFERENCES PRODUCT(pCODE) );

DROP SEQUENCE ORDER_SEQ;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;
DROP TABLE ORDERS;
DESCRIBE MEMBER;
DESCRIBE PRODUCT;
DESCRIBE ORDERS;
SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM ORDERS;


INSERT INTO PRODUCT VALUES('A1', '¸ÆÁÖ', 2000);
INSERT INTO PRODUCT VALUES('B1', '¶¥Äá', 3000); 
INSERT INTO PRODUCT VALUES('A2', '¼ÒÁÖ', 1500); 
INSERT INTO PRODUCT VALUES('B2', '¿ÀÂ¡¾î', 5000);
INSERT INTO PRODUCT VALUES('C1', '±âÀú±Í', 7000);

INSERT INTO MEMBER VALUES('abc', 'DWAYNE JOHNSON', '010-1234-1234');
INSERT INTO MEMBER VALUES('def', 'SHIN SOO CHOO', '010-9876-9876');

INSERT INTO ORDERS(oNUM, rADDRESS, RECIPIENT, oQTY) VALUES(ORDER_SEQ.NEXTVAL, '¼­¿ï ¸¶Æ÷±¸', 'È«±æµ¿', 3);

SELECT oNUM, mID, RECIPIENT, rADDRESS, mPHONE, pCODE, pNAME, pPRICE, 