--[ⅹⅡ] 트랜잭션 명령어 : COMMIT, ROLLBACK, SACEPOINT
-- 데이터처리의 단위, 여러개의 DQL명령문들이 처리되는 논리적인 작업단위
-- 작업의 단위로서 트랜잭션은 데이테의 일관성을 유지하면서 안정적으로 데이터를 복구하도록 도와줌.
COMMIT; -- 새로운 트랜잭션 시작(INSERT, UPDATE, DELETE작업 새로추가될 예정)
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
DESC DEPT01;
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO=40;
SELECT * FROM DEPT01;
ROLLBACK;
-- 마지막으로 실행한 ROLLBACK(혹은 COMMIT) 명령 이후부터 새로운 트랜잭션이 시작됨.
SELECT * FROM DEPT01;
DELETE FROM DEPT01 WHERE DEPTNO = 40;
COMMIT;
-- 새로운 트랜잭션 시작.
SELECT * FROM DEPT01;   -- 현재 DEPTNO 10, 20, 30, 50이 존재
DELETE FROM DEPT01 WHERE DEPTNO = 30;
SELECT * FROM DEPT01;   -- 현재 DEPTNO 10, 20, 50이 존재
SAVEPOINT C1;   -- C1지점 : 10, 20, 50
DELETE FROM DEPT01 WHERE DEPTNO = 20;
SELECT * FROM DEPT01;   -- 10, 50번 부서
SAVEPOINT C2;
DELETE FROM DEPT01 WHERE DEPTNO = 10;
SELECT * FROM DEPT01;   -- 50번 부서
ROLLBACK TO C2; -- ROLLBACK만 실행하면 새로운 트랜잭션 시작 부분으로 돌아감.
