DROP TABLE CUSTOMER;
DROP SEQUENCE CUSTOMER_SQE;

CREATE SEQUENCE CUSTOMER_SQE
        NOCACHE;
        NOCYCLE;
SELECT CUSTOMER_SQE.CURRVAL FROM DUAL;

CREATE TABLE CUS_LEVEL(
    LEVELNO NUMBER(20),
    LEVELNAME VARCHAR2(14) NOT NULL,
    PRIMARY KEY(LEVELNO) );

INSERT INTO CUS_LEVEL VALUES(1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES(2, 'VIP');
INSERT INTO CUS_LEVEL VALUES(3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES(4, 'BLACK');

CREATE TABLE CUSTOMER(
    CNO NUMBER(20),
    CNAME VARCHAR(20) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE,
    PHONE VARCHAR(20),
    POINT NUMBER(20),
    LEVELNO NUMBER(20),
    PRIMARY KEY(CNO),
    UNIQUE(PHONE),
    FOREIGN KEY(LEVELNO) REFERENCES CUS_LEVEL(LEVELNO) );
    
INSERT INTO CUSTOMER 
    VALUES(CUSTOMER_SQE.NEXTVAL, '홍길동', TO_CHAR(TO_DATE('21/06/10', 'YYYY-MM-DD'),'YYYY"-"MM"-"DD'), '010-9999-9999', 0, 1); 
INSERT INTO CUSTOMER 
    VALUES(CUSTOMER_SQE.NEXTVAL, '이철수', TO_CHAR(TO_DATE('20/11/12', 'YYYY-MM-DD'),'YYYY"-"MM"-"DD'), '010-8888-8888', NULL, 2);

-- 프린트 결과를 바꾸기 위해 CREATE TABLE CUSTOMER의 LEVELNO 혹은 INSERT INTODML LEVELNO를 변형하려고 했었음...ㄷㄷㄷ;;;
-- 출력 = 조회(검색)과 마찬가지이므로 SELECT 구문을 활용할 것!
SELECT CNO, CNAME, JOINDATE, PHONE, POINT, LEVELNAME FROM CUSTOMER C, CUS_LEVEL L WHERE L.LEVELNO=C.LEVELNO;
SELECT * FROM CUSTOMER;
DROP SEQUENCE CUSTOMER_SQE;
DROP TABLE CUSTOMER;

SELECT LEVELNAME FROM CUS_LEVEL L, CUSTOMER C WHERE L.LEVELNO=C.LEVELNO AND CNO=1;
COMMIT;